// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $login_cadastro from "./routes/login/cadastro.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $AlertaComponent from "./islands/AlertaComponent.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MessageComponent from "./islands/MessageComponent.tsx";
import * as $login_CadastroIsland from "./islands/login/CadastroIsland.tsx";
import * as $login_LoginIslan from "./islands/login/LoginIslan.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/login/cadastro.tsx": $login_cadastro,
    "./routes/login/index.tsx": $login_index,
  },
  islands: {
    "./islands/AlertaComponent.tsx": $AlertaComponent,
    "./islands/Counter.tsx": $Counter,
    "./islands/MessageComponent.tsx": $MessageComponent,
    "./islands/login/CadastroIsland.tsx": $login_CadastroIsland,
    "./islands/login/LoginIslan.tsx": $login_LoginIslan,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
